### ISSUE TITLE
Problems with other PyAnsys packages compatibilities

### ISSUE THREAD

**Issue by RobPasMue** [pyansys/pydpf-post#107]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

When trying to build the metapackage for all PyAnsys libraries we are encountering certain issues regarding dependencies with ``ansys-dpf-post`` and ``ansys-fluent-visualization``.

Even though the latter is using ``vtk==9.1.0`` (and thus forcing it strictly to a certain vtk version), we were wondering the reason for not allowing it in ``ansys-dpf-post``. This library is explicitly forcing the VTK library to be below 9.1.0 (``vtk<9.1.0``). Would it be possible to remove this strict requirement?

At the moment, ``ansys-dpf-post`` is forcing to use an old version of VTK to the rest of the PyAnsys libraries.

### 📝 Steps to reproduce

-

### 💻 Which operating system are you using?

Linux

### 🐍 Which Python version are you using?

3.9

### 📦 Installed packages

```shell
-
```

**Comment by RobPasMue** [comment]
Pinging @PProfizi for discussion.

**Comment by RobPasMue** [comment]
This has been solved after ``ansys-fluent-visualization`` relaxing its requirements, but it would be interesting that ``pydpf-post`` did not cap the ``vtk`` version below ``9.1.0``. This will affect all other PyAnsys packages. Why is it not possible to handle ``9.1.0``? Can we do something to solve it?

**Comment by PProfizi** [comment]
See [here](https://github.com/pyansys/pydpf-post/actions/runs/2832872084) for errors when removing the vtk<9.1.0 limitation.

**Comment by RobPasMue** [comment]
Pinging @akaszynski for some insights.
