### ISSUE TITLE
Support for Python 3.10

### ISSUE THREAD

**Issue by RobPasMue** [pyansys/pydpf-post#113]
### Description of the feature
Apparently, ``pydpf-post`` is not supported on Python 3.10. On the https://github.com/pyansys/pyansys-landing repository (the PyAnsys metapackage project), we are working on supporting all Python versions from 3.7 onwards. Is there a specific reason for this not to be possible with ``pydpf-post``?

### Steps for implementing the feature
Try supporting Python 3.10. Investigate problematic requirements and needs.

### Useful links and references
No response

**Comment by PProfizi** [comment]
To support Python 3.10, the requirement on vtk<9.1.0 must be suppressed, as can be seen [here](https://github.com/pyansys/pydpf-post/runs/7767065982?check_suite_focus=true).
When deleting the requirement on vtk<9.1.0, we obtain [these errors](https://github.com/pyansys/pydpf-post/actions/runs/2832872084).
