### ISSUE TITLE
Add an issue template specific to documentation

### ISSUE THREAD

**Issue by PProfizi** [pyansys/pydpf-post#159]
### 📝 Description of the feature

A specific issue template for documentation errors would be nice, labeled documentation by default, and not requiring the usual information of the Issue for bugs.
This would be limited to errors on the online documentation.

### 💡 Steps for implementing the feature

Add a template Documentation, see pyansys/pydpf-core#385

**Comment by GuillemBarroso** [comment]
@PProfizi, 

I've found that the templates for new issues in dpf-core are overwriting the ones specified for all pyansys repos located in [here](https://github.com/pyansys/.github/tree/main/.github/ISSUE_TEMPLATE). 

I think that the cleaner way to proceed would be to:

1. Make sure we all agree on the type and content of the issues' templates.
2. Remove templates located in pyansys/dpf-core
3. Update templates in pyansys/.github according to point 1.

I think it would be useful for everyone to have the three templates we have in dpf-core for bug, feature and documentation. Is there anything else we want to add? Do we all agree with this? Am I missing something that really requires to have different templates in dpf-core and post? Also, some other repos (for instance pymapdl) also overwrite templates. Instead, pyfluent follows the ones in pyansys/.gitignore. I really think we should standardize this. 

I am tagging @akaszynski, @jorgepiloto, @germa89, @RobPasMue, @MaxJPRey for further input on this.

**Comment by PProfizi** [comment]
> @PProfizi,
> 
> I've found that the templates for new issues in dpf-core are overwriting the ones specified for all pyansys repos located in [here](https://github.com/pyansys/.github/tree/main/.github/ISSUE_TEMPLATE).
> 
> I think that the cleaner way to proceed would be to:
> 
> 1. Make sure we all agree on the type and content of the issues' templates.
> 2. Remove templates located in pyansys/dpf-core
> 3. Update templates in pyansys/.github according to point 1.
> 
> I think it would be useful for everyone to have the three templates we have in dpf-core for bug, feature and documentation. Is there anything else we want to add? Do we all agree with this? Am I missing something that really requires to have different templates in dpf-core and post? Also, some other repos (for instance pymapdl) also overwrite templates. Instead, pyfluent follows the ones in pyansys/.gitignore. I really think we should standardize this.
> 
> I am tagging @akaszynski, @jorgepiloto, @germa89, @RobPasMue, @MaxJPRey for further input on this.

@GuillemBarroso As far as PyDPF-Core and PyDPF-Post are concerned, I did customize the Bug template a bit to add a required check promoting the Compatibility section of the documentation so people get directed there.
IMO the default pyansys templates are a perfect starting point for any project, yet having customized templates in some projects cannot be avoided.

I am not sure one can customize only one template and use the organization ones for the others though. I think that is why I duplicated the "Enhancements" template.

**Comment by GuillemBarroso** [comment]
@PProfizi, I see your point in wanting a customized issue template. 

I am going to add the documentation template issue in the pyansys templates so everyone has the option to chose it. Then, if someone wants a customized one they just add their yml file in their repos.

**Comment by germa89** [comment]
> @PProfizi, I see your point in wanting a customized issue template.
> 
> I am going to add the documentation template issue in the pyansys templates so everyone has the option to chose it. Then, if someone wants a customized one they just add their yml file in their repos.

I agree with this. Repos with already customized templates might need to copy it into their repos, but it is good to have a default.

**Comment by MaxJPRey** [comment]
Thanks @GuillemBarroso for adding it to the DPF templates.
