### ISSUE TITLE
Improve print of ``DataObject``

### ISSUE THREAD

**Issue by GuillemBarroso** [pyansys/pydpf-post#235]
### Description of the feature

A [previous PR](https://github.com/pyansys/pydpf-post/pull/233) implemented the ``__str__`` method for the class ``DataObject``.

This should be improved to hide all references to ``Field`` and ``FieldsContainer``. 

### Steps for implementing the feature

Modify ``__srt__`` method in ``DataObject`` to display all relevant information.

### Useful links and references

N/A

**Comment by PProfizi** [comment]
Closing as stale. 
str representations of Fields and FieldsContainers are being modified server-side.
