### ISSUE TITLE
Extend ``as_data_frame()`` method for more than one field

### ISSUE THREAD

**Issue by GuillemBarroso** [pyansys/pydpf-post#241]
### Description of the feature

The ``DataObject`` method ``as_data_frame()`` is currently only implemented for FieldsContainers with only one Field.

This should be extended to any number of fields.

### Steps for implementing the feature

Modify the ``as_data_frame()`` method to be able to accept ``FieldsContainers`` with more than one ``Field``.

### Useful links and references

N/A

**Comment by PProfizi** [comment]
Closing as stale
