### ISSUE TITLE
Bug located in ...

### ISSUE THREAD

**Issue by jerryjaison** [pyansys/pydpf-post#285]
### Before submitting the issue

- [X] I have checked for [Compatibility](https://dpf.docs.pyansys.com/getting_started/index.html#compatibility) issues
- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

While running pyvista plots in Jupyter notebook. I am facing the below given issue. 

![jupyter](https://user-images.githubusercontent.com/104209582/218379152-223dcfd2-f8f1-4126-ab64-78ac05301ef3.PNG)

I am not able to do the 3D view of the model in this case. 

### Steps To Reproduce

Please rerun the code given below in jupyter notebook. 

import numpy as np
import pyvista as pv
from pyvista import examples

mesh = examples.load_hexbeam()
cpos = [(6.20, 3.00, 7.50),
        (0.16, 0.13, 2.65),
        (-0.28, 0.94, -0.21)]

pl = pv.Plotter()
pl.add_mesh(mesh, show_edges=True, color='white')
pl.add_points(mesh.points, color='red',
              point_size=20)
pl.camera_position = cpos
pl.show()

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.10

### Installed packages

aiofiles==22.1.0
aiosqlite==0.18.0
ansys-api-mapdl==0.5.1
ansys-api-platform-instancemanagement==1.0.0b3
ansys-dpf-core==0.7.2
ansys-dpf-gate==0.3.0
ansys-dpf-gatebin==0.3.0
ansys-dpf-post==0.2.5
ansys-grpc-dpf==0.7.0
ansys-mapdl-core==0.64.0
ansys-mapdl-reader==0.52.8
ansys-platform-instancemanagement==1.0.3
anyio==3.6.2
appdirs==1.4.4
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
arrow==1.2.3
asttokens==2.2.1
attrs==22.2.0
Babel==2.11.0
backcall==0.2.0
beautifulsoup4==4.11.2
bleach==6.0.0
cachetools==5.3.0
certifi==2022.12.7
cffi==1.15.1
charset-normalizer==2.1.1
click==8.1.3
colorama==0.4.6
comm==0.1.2
contourpy==1.0.7
cycler==0.11.0
debugpy==1.6.6
decorator==5.1.1
defusedxml==0.7.1
executing==1.2.0
fastjsonschema==2.16.2
fonttools==4.38.0
fqdn==1.5.1
frozenlist==1.3.3
geomdl==5.3.1
google-api-core==2.11.0
google-api-python-client==2.77.0
google-auth==2.16.0
google-auth-httplib2==0.1.0
googleapis-common-protos==1.58.0
grpcio==1.51.1
httplib2==0.21.0
idna==3.4
imageio==2.25.0
importlib-metadata==6.0.0
ipykernel==6.21.1
ipython==8.9.0
ipython-genutils==0.2.0
ipywidgets==8.0.4
isoduration==20.11.0
jedi==0.18.2
Jinja2==3.1.2
json5==0.9.11
jsonpointer==2.3
jsonschema==4.17.3
jupyter==1.0.0
jupyter-console==6.4.4
jupyter-events==0.5.0
jupyter-ydoc==0.2.2
jupyter_client==8.0.2
jupyter_core==5.2.0
jupyter_server==2.2.1
jupyter_server_fileid==0.6.0
jupyter_server_terminals==0.4.4
jupyter_server_ydoc==0.6.1
jupyterlab==3.6.1
jupyterlab-pygments==0.2.2
jupyterlab-widgets==3.0.5
jupyterlab_server==2.19.0
kiwisolver==1.4.4
MarkupSafe==2.1.2
matplotlib==3.6.3
matplotlib-inline==0.1.6
mistune==2.0.5
multidict==6.0.4
nbclassic==0.5.1
nbclient==0.7.2
nbconvert==7.2.9
nbformat==5.7.3
nest-asyncio==1.5.6
notebook==6.5.2
notebook_shim==0.2.2
numpy==1.23.5
packaging==23.0
pandocfilters==1.5.0
parso==0.8.3
pickleshare==0.7.5
Pillow==9.4.0
platformdirs==3.0.0
pooch==1.6.0
prometheus-client==0.16.0
prompt-toolkit==3.0.36
protobuf==3.20.3
protoc-gen-swagger==0.1.0
psutil==5.9.4
pure-eval==0.2.2
pyansys-tools-versioning==0.3.3
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.21
Pygments==2.14.0
pyiges==0.2.1
pyparsing==3.0.9
pyrsistent==0.19.3
python-dateutil==2.8.2
python-json-logger==2.0.4
pytz==2022.7.1
pyvista==0.38.1
pywin32==305
pywinpty==2.0.10
PyYAML==6.0
pyzmq==25.0.0
qtconsole==5.4.0
QtPy==2.3.0
requests==2.28.2
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rsa==4.9
scipy==1.10.0
scooby==0.7.1
Send2Trash==1.8.0
six==1.16.0
sniffio==1.3.0
soupsieve==2.3.2.post1
stack-data==0.6.2
terminado==0.17.1
tinycss2==1.2.1
tornado==6.2
tqdm==4.64.1
traitlets==5.9.0
trame-client==2.5.1
trame-components==2.1.0
trame-deckgl==2.0.1
trame-markdown==2.0.2
trame-matplotlib==2.0.1
trame-plotly==2.1.0
trame-router==2.0.1
trame-simput==2.2.5
trame-vega==2.0.2
trame-vtk==2.0.17
trame-vuetify==2.1.0
uri-template==1.2.0
uritemplate==4.1.1
urllib3==1.26.14
vtk==9.2.5
wcwidth==0.2.6
webcolors==1.12
webencodings==0.5.1
websocket-client==1.5.1
widgetsnbextension==4.0.5
y-py==0.5.5
ypy-websocket==0.8.2
zipp==3.12.1

**Comment by PProfizi** [comment]
Hi @jerryjaison! Due to this error being linked only with using pyvista in a jupyter environment, I will be transferring this issue to the pyvista project.

**Comment by PProfizi** [comment]
Hey @akaszynski, pinging just in case you might have a quick answer.

**Comment by akaszynski** [comment]
Please run:
```
pip install pyvista[jupyter]
```

This will install all the jupyter notebook plotting requirements. These are optional to make a lighter initial install.
