### ISSUE TITLE
return Plotter-object instead of showing plot

### ISSUE THREAD

**Issue by natter1** [pyansys/pydpf-post#36]
`plastic_strain.plot_contour()`
Similar to pymapdl it would be great to get the plotter object instead of automatically show a plot and returning `None` - without any chance to customize a plot. Also themes should be supported.

**Comment by akaszynski** [comment]
That's something we can look into.  Agreed that it's more helpful to have the plotter object rather than the straight plot.  One thing to consider is sharing the `general_plotter` contained within PyMAPDL across multiple libraries rather than copy/pasting it.

**Comment by anslpa** [comment]
Hi, it is now possible to instantiate a DpfPlotter to manipulate using the ansys-dpf-core module.
