### ISSUE TITLE
No module named 'ansys.dpf'

### ISSUE THREAD

**Issue by seghier** [pyansys/pydpf-post#40]
I use python 3.7 and i install all modules but this error appears

```
from ansys.dpf import post
from ansys.dpf.post import examples
solution = post.load_solution(examples.multishells_rst)
stress = solution.stress()
stress.xx.plot_contour(show_edges=False)
```

```
from ansys.dpf import post
ModuleNotFoundError: No module named 'ansys.dpf'; 'ansys' is not a package
```

**Comment by rlagha** [comment]
Hi @seghier 
what do you get when you do: pip show ansys.dpf.core

**Comment by seghier** [comment]
Hi @rlagha 
I get this message
I have ansys student version
```
Name: ansys-dpf-core
Version: 0.3.0
Summary: DPF Python gRPC client
Home-page: UNKNOWN
Author: None
Author-email: None
License: UNKNOWN
Location: c:\python37\lib\site-packages
Requires: ansys.grpc.dpf, progressbar2, psutil, numpy
Required-by: ansys-dpf-post
```

**Comment by rlagha** [comment]
@seghier , may I ask you to try with Anaconda 3 and jupyter lab?

**Comment by jlcuadros** [comment]
Just for information I have no problems with anaconda python 3.7 and pycharm, I can run and debug without problems
![2021-12-10 10_21_28-dpf_learning – aaa py Administrator](https://user-images.githubusercontent.com/16316084/145549995-8b5a45a5-2bde-4ccf-8478-87efe77d8328.png)
![2021-12-10 10_24_19-Settings](https://user-images.githubusercontent.com/16316084/145550247-66e05305-6f5e-48d4-b1d6-a48f310a6988.png)

Other case is with ironpython, I cant debug so I needed to download Visual Studio 2022

Regards

Jose Luis

**Comment by PProfizi** [comment]
Hi @seghier, this looks like the latest error you got was due to DPF not finding the server executable. Could you please check your AWP_ROOT environment variable? It is used to define the ansys_path argument which should point to a Ans.Dpf.Grpc.exe in your ANSYS install.

**Comment by PProfizi** [comment]
Closing as stale. Please reopen if still relevant.

**Comment by kunal-3196** [comment]
hello, comment that step still the code runs.

**Comment by jmaravin** [comment]
Hi, I get a very similar error but with pyaedt when using Visual Studio code. 
I get the following error message: 
_ModuleNotFoundError: No module named 'pyaedt'_

I think I have installed the modules correctly but when I run the commnad mentioned above (**_pip show ansys.pyaedt.core_**), I get the following error message: 

_WARNING: Package(s) not found: ansys.pyaedt.core_

**Comment by PProfizi** [comment]
Hello @jmaravin, what you can do is first check the module is indeed correctly installed, using `pip list`.
If the `pip show` command does not work, I would suggest that either the module was not correctly installed, or that it is not named `ansys.pyaedt.core` but rather something such as `pyaedt``

**Comment by jmaravin** [comment]
Hi @PProfizi it works now. What I did was to reinstall everything and worked well. 
Thanks very much. 
Regards, 
Jaime
