### ISSUE TITLE
mapping results across bodies

### ISSUE THREAD

**Issue by mcMunich** [pyansys/pydpf-post#45]
There is an apdl function to map results across bodies/surfaces using a 3D interpolation:
https://ansyshelp.ansys.com/account/Secured?returnurl=/Views/Secured/corp/v212/en/ans_cmd/Hlp_C_MOPER.html
*MOPER, ParR, Par1, MAP
This command will map results from one set of points to another (Par1 to ParR)
So this is an APDL function that post processes. 
This is used for meshes that don't share topologies and can be used to present results that are not included in the rst. 
Is there a way to do this with dpf?

**Comment by anslpa** [comment]
Hi, latest enhancements of PyDPF-Core now allow to plot results mapped on a specific PATH of coordinates. More information can be found under PyDPF-Core documentation, in the "Examples/Plotting Examples" section.
