### ISSUE TITLE
Save plot to file

### ISSUE THREAD

**Issue by mcMunich** [pyansys/pydpf-post#56]
This is probably something I just couldn't find in the documentation, but how can I save a result plot to file, preferably something I can share, like a jpg or png.
I found a save_as_vtk possibility but that is not something shareable or at least I have never seen it (not quite sure what it does, or how to use it).
![image](https://user-images.githubusercontent.com/84008975/145787442-4a2b4ca4-9040-41ba-a85d-b77bc5c5a2b6.png)
A related issue that needs to be dealt with simultaneously would be the fact that my IDE is locked until I close a plot (and therefore can't use command after generating a plot to save unless I first close the plot).

**Comment by rlagha** [comment]
Hi @mcMunich , thanks for the suggestion, I think that we can easily add the image export capability. @anslpa

**Comment by mcMunich** [comment]
@anslpa thanks for the link. But that solution does not seem to work. I don't find a my_screenshot.png anywhere.

**Comment by anslpa** [comment]
Hi @mcMunich, the pull request needs to be merged before the example script is usable. I'll update this issue once this is done.

**Comment by mcMunich** [comment]
@anslpa Great. I will test it when it is updated. Thanks.
