### ISSUE TITLE
AttributeError 

### ISSUE THREAD

**Issue by ftopak** [pyansys/pydpf-post#57]
Hello, I'm using Jupyter and not used pyansys before. I was hoping to use it for post-processing some Fluent result data but could not even get started.

When I try following code:

    from ansys.dpf import post
    from ansys.dpf.post import examples
    simple_bar = examples.simple_bar
    solution = post.load_solution(simple_bar)

I get the following error. What could be the reason?

      AttributeError                            Traceback (most recent call last)
      <ipython-input-8-2d09e3b33294> in <module>
            1 simple_bar = examples.simple_bar
      ----> 2 solution = post.load_solution(simple_bar)
      
      ~\anaconda3\lib\site-packages\ansys\dpf\post\post_utility.py in load_solution(data_sources, physics_type, analysis_type)
           44     """
           45     _model = Model(data_sources)
      ---> 46     data_sources = _model.metadata.data_sources
           47 
           48     if not physics_type:
      
      ~\anaconda3\lib\site-packages\ansys\dpf\core\model.py in metadata(self)
          101         """
          102         if not self._metadata:
      --> 103             self._metadata = Metadata(self._data_sources, self._server)
          104         return self._metadata
          105 
      
      ~\anaconda3\lib\site-packages\ansys\dpf\core\model.py in __init__(self, data_sources, server)
          244     def __init__(self, data_sources, server):
          245         self._server = server
      --> 246         self._set_data_sources(data_sources)
          247         self._meshed_region = None
          248         self._result_info = None
      
      ~\anaconda3\lib\site-packages\ansys\dpf\core\model.py in _set_data_sources(self, var_inp)
          372         else:
          373             self._data_sources = DataSources(server=self._server)
      --> 374         self._cache_streams_provider()
          375 
          376     def _load_result_info(self):
      
      ~\anaconda3\lib\site-packages\ansys\dpf\core\model.py in _cache_streams_provider(self)
          267             )
          268         else:
      --> 269             self._stream_provider = Operator("stream_provider", server=self._server)
          270             self._stream_provider.inputs.connect(self._data_sources)
          271 
      
      ~\anaconda3\lib\site-packages\ansys\dpf\core\dpf_operator.py in __init__(self, name, config, server)
           76 
           77         # add dynamic inputs
      ---> 78         if len(self._message.spec.map_input_pin_spec) > 0 and self._inputs == None:
           79             self._inputs = Inputs(self._message.spec.map_input_pin_spec, self)
           80         if len(self._message.spec.map_output_pin_spec) != 0 and self._outputs == None:
      
      AttributeError: spec

**Comment by rlagha** [comment]
Hi @ftopak please could you pip uninstall ansys.dpf.core and pip uninstall ansys.grpc.dpf. And then install ansys.dpf.core?

we had an issue today with a mismatch of versions and pushed a new version 0.3.5 for ansys.dpf.core. 
you should have 0.3.5 for ansys.dpf.core and 0.3.0 for ansys.grpc.dpf.

Thanks
Ramdane

**Comment by ftopak** [comment]
Hi Ramdane,

Your suggestion worked, thanks!
