### ISSUE TITLE
notebook = False does not work for contour plots with Jupiter Notebook

### ISSUE THREAD

**Issue by vishnuramn** [pyansys/pydpf-post#59]
You can use the below code to replicate the issue

`
>>> from ansys.dpf import post
>>> from ansys.dpf.post import examples
>>> solution = post.load_solution(examples.multishells_rst)
>>> stress = solution.stress()
>>> stress.xx.plot_contour(show_edges=False,notebook=False)
`

This seems to be a problem only in Jupiter notebook .
This works well for elemental plots and seems to be a problem only for contour plots

**Comment by PProfizi** [comment]
@vishnuramn see https://github.com/pyansys/pydpf-core/pull/259 for core commands. I am now fixing the PyDPF-Post ResultData.plot_contour.
