### ISSUE TITLE
Specifying the ANSYS version default path.

### ISSUE THREAD

**Issue by LetoTheJust** [pyansys/pydpf-post#78]
### Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### Description of the bug

I have multiple versions of ANSYS installed. When I try to run ansys.dpf.post I am getting the: InvalidANSYSVersionError: Ansys v192 does not support DPF. How can I specify default path for ansys.dpf? Similar as in mapdl: pymapdl.change_default_ansys_path(new_path)

### Steps To Reproduce

```
from ansys.dpf import post
from ansys.dpf.post import examples
solution = post.load_solution(examples.multishells_rst)
```

### Which Operating System are you using?

Windows

### Which Python version are you using?

3.8

### Installed packages

not relevant

**Comment by PProfizi** [comment]
Hello @LetoTheJust. 
DPF requires the AWP_ROOT environment variable which should have been set during installation of ANSYS Workbench. 
This tells DPF where to look for ANSYS installations, and then DPF is supposed to choose the most recent installation it finds there.
Are all of your ANSYS versions installed where AWP_ROOT points to?

**Comment by PProfizi** [comment]
@LetoTheJust what you can do to select the ANSYS version you want to use, is start the server manually using `ansys.dpf.core.server.start_local_server(ansys_path='path-to-your-install')` right after your imports.
However here DPF should detect the latest version of ANSYS available at AWP_ROOT and use it.
Still, I will look into implementing a command to choose which ANSYS version to use.

**Comment by bedermaus** [comment]
@PProfizi getting same error.

```py
import matplotlib.pyplot as plt
import numpy as np

from ansys.dpf import core as dpf
from ansys.dpf.core import examples
from ansys.dpf.core import operators as ops

transient = examples.download_transient_result()
model = dpf.Model(transient)
print(model)
```

Error:
`ValueError: Unable to automatically locate the Ansys path  for version 221.Manually enter one when starting the server or set it as the environment variable "ANSYS_PATH"`

As you said below tried to add server
1)`dpf.server.start_local_server(ansys_path='B:/ANSYS Inc/v211/ansys/bin/winx64/ansys2021R1.exe')`
2)`dpf.server.start_local_server(ansys_path='B:/ANSYS Inc/v211/')`
3)`dpf.server.start_local_server(ansys_path='B:/ANSYS Inc/v211/ansys/bin/winx64/ANSYS.exe')`
4)`dpf.server.start_local_server(ansys_path='B:/ANSYS Inc/v211/ansys/bin/winx64/ANSYS211.exe')`

Same errors.
`NotADirectoryError: Invalid Ansys path "B:\ANSYS Inc\v211\ansys\bin\winx64\ansys2021R1.exe"`

**Comment by PProfizi** [comment]
Hi @bedermaus 

So the right way of doing it is indeed case 2), as ansys_path should point to the vXXX folder. 
DPF will then try to run vXXX/aisol/bin/winx64/Ans.Dpf.Grpc.bat
The error you get tells me DPF went all the way to trying to run this file but it was not found.
Could you please first check it is indeed there?

BTW if you are trying to use ANSYSR211, then only versions 0.2.* of PyDPF-Core are compatible.

**Comment by bedermaus** [comment]
@PProfizi Thanks, didnt notice a version.
Installed 0.2.1, all works...
But unfortunately there is no "operators" class.
Is it possible to use even 0.3.* version with Ansys 2021R1?

**Comment by PProfizi** [comment]
@bedermaus sadly I think not, at least according to the compatibility table.

IMO there was a mistake in not incrementing the major version value when this happened. That might have made it clearer that retrocompatibility is ensured only starting with Ansys 2021R2.

**Comment by bedermaus** [comment]
@PProfizi So its not possible to obtain minimum and maximum displacements for all results in version lower than 2021R1??

**Comment by PProfizi** [comment]
@bedermaus, for Ansys 2021R1, with PyDPF-Core 0.2.*, one can instantiate an operator as shown in the example in the dosctring [here](https://github.com/pyansys/pydpf-core/blob/cdefeb4d8bb537d4a41eb9e0fecf0698170e2de9/ansys/dpf/core/dpf_operator.py#L37) using the "internal name" shown in the [operator documentation](https://dpfdocs.pyansys.com/operator_reference.html), for example for the min_max operator:
![image](https://user-images.githubusercontent.com/100710998/171628005-989cf9da-78fb-4fb7-ae11-02281ceaddb4.png)


The result if you want to create a min_max operator should be:
`min_max_op = dpf.core.Operator('min_max')`

Yet, indeed, the only documentation live is the one for the latest version, something we will change soon with a drop-down menu enabling users to see the documentation specific to their package version.
If you want, you can actually build the documentation for 0.2.1 by downloading the source and using the "build_doc.bat" script therein.
However if you prefer I can generate it and try to upload it somewhere while we work on having all documentation versions live.


For Ansys 2021R2 and above, one can use the operators the way described in the up-to-date documentation.

DPF is not available for Ansys versions below 2021R1.

**Comment by bedermaus** [comment]
@PProfizi thanks a lot, it works.
About drop-down menu with versions - i think its good idea for future, but i don't think that a lot of users use old version, so don't waste time on it

**Comment by PProfizi** [comment]
Hi @bedermaus , you should be able to use the `op=dpf.core.Operator('rescope')` operator, giving it a nodal scoping on the nodes of interest `op.inputs.mesh_scoping.connect(my_mesh_scoping)`, made using [ansys.dpf.core.mesh_scoping_factory.nodal_scoping](https://dpf.docs.pyansys.com/api/ansys.dpf.core.mesh_scoping_factory.html#ansys.dpf.core.mesh_scoping_factory.nodal_scoping).

**Comment by PProfizi** [comment]
Closing the issue regarding specifying the ANSYS version default path, which should now be done via the `ANSYS_DPF_PATH` environment variable.
